### ISSUE TITLE
Trying to build proto.c|.h files

### ISSUE THREAD

**Issue by barbiani** [rideskip/anchor#3]
Hello,
 
I am trying to include sonar into another project and am getting in trouble with 'option (nanopb_msgopt).msgid = 0x264;'

```
Compiling sonar_extensions.pb.c
Compiling DeviceInfo.pb.c
Traceback (most recent call last):
  File "/home/barbiani/x/components/sonar/protobuf/sonar_proto_gen.py", line 125, in <module>
    run()
  File "/home/barbiani/x/components/sonar/protobuf/sonar_proto_gen.py", line 118, in run
    response = process_request(request)
  File "/home/barbiani/x/components/sonar/protobuf/sonar_proto_gen.py", line 105, in process_request
    raise Exception("Unknown target language (parameter=%s)"%(request.parameter))
Exception: Unknown target language (parameter=)
--sonar_out: protoc-gen-sonar: Plugin failed with status code 1.
make: *** [sonar_nanopb.mk:27: DeviceInfo.pb.c] Error 1
```

DeviceInfo.proto:
```
syntax = "proto2";

import "sonar_extensions.proto";
import "nanopb.proto";

message DeviceInfo {
    option (nanopb_msgopt).msgid = 0x264;
    option (sonar_msgopt).attr_ops = ATTR_OPS_R;

    enum HardwareRevision {
        UNKNOWN = 0;
        EVT = 1;
        DVT = 2;
        PVT = 3;
    }

    required HardwareRevision hardware_revision = 1;
    required string serial = 2 [(nanopb).max_size = 25];
```

**Comment by barbiani** [comment]
Hello,
 
I am trying to include sonar into another project and am getting in trouble with 'option (nanopb_msgopt).msgid = 0x264;'

```
Compiling sonar_extensions.pb.c
Compiling DeviceInfo.pb.c
Traceback (most recent call last):
  File "/home/barbiani/x/components/sonar/protobuf/sonar_proto_gen.py", line 125, in <module>
    run()
  File "/home/barbiani/x/components/sonar/protobuf/sonar_proto_gen.py", line 118, in run
    response = process_request(request)
  File "/home/barbiani/x/components/sonar/protobuf/sonar_proto_gen.py", line 105, in process_request
    raise Exception("Unknown target language (parameter=%s)"%(request.parameter))
Exception: Unknown target language (parameter=)
--sonar_out: protoc-gen-sonar: Plugin failed with status code 1.
make: *** [sonar_nanopb.mk:27: DeviceInfo.pb.c] Error 1
```

DeviceInfo.proto:
```
syntax = "proto2";

import "sonar_extensions.proto";
import "nanopb.proto";

message DeviceInfo {
    option (nanopb_msgopt).msgid = 0x264;
    option (sonar_msgopt).attr_ops = ATTR_OPS_R;

    enum HardwareRevision {
        UNKNOWN = 0;
        EVT = 1;
        DVT = 2;
        PVT = 3;
    }

    required HardwareRevision hardware_revision = 1;
    required string serial = 2 [(nanopb).max_size = 25];
```

**Comment by barbiani** [comment]
The company is no longer in business.

The example has some cut-and-paste errors and the makefile does not pass the plugin the 'c' parameter.

**Comment by bgomberg** [comment]
Hi @barbiani,

Sorry for not seeing this earlier. As you noted, this organization doesn't exist anymore, so I have instead been maintaining my own fork [here](https://github.com/bgomberg/anchor) which should be considered the primary fork at this point. I'm not currently using the SONAR component of this library so haven't made any changes versus this one, but happy to answer any questions on it there if you're still interested and/or actively using it.

I've also updated the README here to note this moving forward.
